"""S3-compatible dual-bucket object storage via boto3 (MinIO, AWS S3, etc.).

Bucket architecture:
  images                → embedded images from documents (private, presigned URL access)
  knowledge-documents   → original uploaded documents + canonical JSON (private, presigned URL access)

Both buckets are PRIVATE. All access goes through presigned URLs generated by the application API.
"""
import os
import re
import time
import json
import uuid
from datetime import datetime
from typing import Optional
from loguru import logger
from app.core.config import settings

try:
    import boto3
    from botocore.config import Config
    HAS_BOTO3 = True
except ImportError:
    boto3 = None
    Config = None
    HAS_BOTO3 = False


# ─── Bucket Names ─────────────────────────────────────────────────────────────

def _images_bucket() -> str:
    """Bucket for embedded images extracted from documents."""
    return os.getenv("S3_BUCKET") or settings.S3_BUCKET or "images"


def _docs_bucket() -> str:
    """Bucket for original uploaded documents and canonical JSON."""
    return os.getenv("S3_DOCUMENTS_BUCKET") or settings.S3_DOCUMENTS_BUCKET or "knowledge-documents"


def _staging_bucket() -> str:
    """Bucket for staging/pending JSON documents under review."""
    return os.getenv("S3_STAGING_BUCKET") or getattr(settings, "S3_STAGING_BUCKET", "staging") or "staging"


def _approved_bucket() -> str:
    """Bucket for approved/published canonical JSON documents."""
    return os.getenv("S3_APPROVED_BUCKET") or getattr(settings, "S3_APPROVED_BUCKET", "approved") or "approved"


# ─── S3 Client ─────────────────────────────────────────────────────────────────

_cached_client = None
_last_client_check_time = 0

def _save_file_to_local_disk(content: bytes, filename: str, s3_key: str = None) -> None:
    """Saves binary content to local disk fallback directory only when MinIO is unavailable."""
    if not content:
        return
    try:
        folder = "data/storage"
        os.makedirs(folder, exist_ok=True)
        fname = os.path.basename(filename)
        local_path = os.path.join(folder, fname)
        with open(local_path, "wb") as f:
            f.write(content)
        if s3_key:
            s3_fname = os.path.basename(s3_key)
            if s3_fname != fname:
                with open(os.path.join(folder, s3_fname), "wb") as f:
                    f.write(content)
    except Exception as e:
        logger.debug(f"Local disk fallback write exception for '{filename}': {e}")


def _get_client():
    """
    Creates boto3 S3 client with automatic fallback across docker network (http://minio:9000)
    and host localhost (http://localhost:9000), cached for performance.
    If MinIO/S3 is unreachable, returns None cleanly to enable local storage fallback.
    """
    global _cached_client, _last_client_check_time
    now = time.time()
    if _cached_client is not None:
        return _cached_client if _cached_client is not False else None

    # Don't retry list_buckets continuously if it failed recently (< 30s)
    if now - _last_client_check_time < 30 and _cached_client is False:
        return None

    _last_client_check_time = now

    if not HAS_BOTO3:
        _cached_client = False
        return None

    endpoints = []
    env_endpoint = os.getenv("S3_ENDPOINT_URL") or settings.S3_ENDPOINT_URL
    if env_endpoint:
        endpoints.append(env_endpoint)
    for ep in ["http://minio:9000", "http://localhost:9000", "http://127.0.0.1:9000"]:
        if ep not in endpoints:
            endpoints.append(ep)

    access_key = os.getenv("S3_ACCESS_KEY") or settings.S3_ACCESS_KEY or "minioadmin"
    secret_key = os.getenv("S3_SECRET_KEY") or settings.S3_SECRET_KEY or "minioadmin"
    region = os.getenv("S3_REGION") or settings.S3_REGION or "us-east-1"
    use_path_style = settings.S3_USE_PATH_STYLE if hasattr(settings, "S3_USE_PATH_STYLE") else True

    for endpoint_url in endpoints:
        try:
            client = boto3.client(
                "s3",
                endpoint_url=endpoint_url,
                aws_access_key_id=access_key,
                aws_secret_access_key=secret_key,
                config=Config(
                    signature_version="s3v4",
                    s3={"addressing_style": "path" if use_path_style else "auto"},
                    connect_timeout=2.0,
                    read_timeout=15.0,
                    retries={'max_attempts': 2}
                ),
                region_name=region,
            )
            client.list_buckets()
            was_offline = (_cached_client is False)
            _cached_client = client
            if was_offline:
                logger.info("🟢 MinIO connection restored! Triggering auto-sync of fallback local files to MinIO...")
                try:
                    sync_existing_local_to_minio(client=client)
                except Exception as sync_e:
                    logger.warning(f"Error during auto-sync to MinIO: {sync_e}")
            return client
        except Exception:
            continue

    _cached_client = False
    logger.info("MinIO S3 service offline or unreachable. Storage operating in seamless local disk mode.")
    return None


# ─── Bucket Initialization ────────────────────────────────────────────────────

def _ensure_bucket_private(bucket_name: str) -> None:
    """Ensures a MinIO bucket exists with PRIVATE access (no public read)."""
    client = _get_client()
    if not client:
        return
    try:
        try:
            client.head_bucket(Bucket=bucket_name)
        except Exception:
            client.create_bucket(Bucket=bucket_name)
            logger.info(f"Created MinIO bucket (private): '{bucket_name}'")
    except Exception as e:
        logger.debug(f"Could not connect or ensure MinIO bucket '{bucket_name}': {e}")


def _ensure_images_bucket() -> None:
    """Ensures images bucket exists with PUBLIC-READ policy so URLs never expire."""
    bucket_name = _images_bucket()
    try:
        client = _get_client()
        try:
            client.head_bucket(Bucket=bucket_name)
        except Exception:
            client.create_bucket(Bucket=bucket_name)
            logger.info(f"Created MinIO bucket: '{bucket_name}'")

        # Set public read policy so browser/frontend can view images directly
        # Images use STATIC URLs that never expire — not presigned URLs
        policy = {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Principal": "*",
                    "Action": ["s3:GetObject"],
                    "Resource": [f"arn:aws:s3:::{bucket_name}/*"]
                }
            ]
        }
        try:
            client.put_bucket_policy(Bucket=bucket_name, Policy=json.dumps(policy))
        except Exception:
            pass
    except Exception as e:
        logger.warning(f"Could not ensure images bucket '{bucket_name}': {e}")


def _ensure_docs_bucket() -> None:
    """Ensures knowledge-documents bucket exists with PRIVATE access."""
    _ensure_bucket_private(_docs_bucket())


def _ensure_staging_bucket() -> None:
    """Ensures staging bucket exists with PRIVATE access."""
    _ensure_bucket_private(_staging_bucket())


def _ensure_approved_bucket() -> None:
    """Ensures approved bucket exists with PRIVATE access."""
    _ensure_bucket_private(_approved_bucket())


def _build_static_image_url(bucket_name: str, s3_key: str) -> str:
    """
    Builds a static (non-expiring) image URL for the public-read images bucket.
    Uses localhost:9000 for browser access (converts docker-internal minio:9000).
    """
    # Always return browser-accessible URL
    return f"http://localhost:9000/{bucket_name}/{s3_key}"


def ensure_all_buckets() -> None:
    """Initialize all 4 buckets at application startup.
    - images: PUBLIC-READ (static URLs, never expire)
    - knowledge-documents: PRIVATE (presigned URLs only)
    - staging: PRIVATE (staged/pending JSON documents)
    - approved: PRIVATE (approved/published canonical JSON documents)
    """
    _ensure_images_bucket()
    _ensure_docs_bucket()
    _ensure_staging_bucket()
    _ensure_approved_bucket()
    logger.info(
        f"MinIO buckets initialized: '{_images_bucket()}' (public-read), "
        f"'{_docs_bucket()}' (private), '{_staging_bucket()}' (private), '{_approved_bucket()}' (private)"
    )
    # Sync any pre-existing local disk pending/output files into MinIO source of truth
    sync_existing_local_to_minio()


# ─── Presigned URL Generation ─────────────────────────────────────────────────

def _generate_presigned_url(bucket_name: str, s3_key: str, expires: int = 604800) -> str:
    """
    Generates presigned GET URL for an S3 object.
    All access is via presigned URLs (both buckets are PRIVATE).
    Default expiry: 7 days for images, callers can override.
    """
    try:
        client = _get_client()
        raw_url = client.generate_presigned_url(
            "get_object",
            Params={"Bucket": bucket_name, "Key": s3_key},
            ExpiresIn=expires
        )
        # Convert docker-internal URL to browser-accessible URL
        if "minio:9000" in raw_url:
            raw_url = raw_url.replace("minio:9000", "localhost:9000")
        return raw_url
    except Exception as e:
        logger.warning(f"Failed to generate presigned URL for '{bucket_name}/{s3_key}': {e}")
        return f"http://localhost:9000/{bucket_name}/{s3_key}"


def _format_browser_url(raw_url: str = None, s3_key: str = "") -> str:
    """
    Ensures image URL is accessible by the doctor's browser across all network environments:
    1. If S3_PUBLIC_URL is configured (e.g. 'https://domain.com/api/storage' or CDN), use that.
    2. If raw_url is a valid external HTTP(S) URL (not internal minio:9000 or localhost:9000), use that.
    3. Otherwise, returns universal relative backend proxy path '/api/storage/{s3_key}' streamed via FastAPI.
    """
    clean_key = (s3_key or "").lstrip("/")
    if hasattr(settings, "S3_PUBLIC_URL") and settings.S3_PUBLIC_URL and str(settings.S3_PUBLIC_URL).strip():
        base = str(settings.S3_PUBLIC_URL).rstrip("/")
        if clean_key:
            return f"{base}/{clean_key}"

    if raw_url and isinstance(raw_url, str) and raw_url.startswith("http"):
        if not any(internal_host in raw_url for internal_host in ["minio:9000", "localhost:9000", "127.0.0.1:9000"]):
            return raw_url

    # Universal proxy path served by FastAPI backend (supports doctor interface across all IP addresses)
    if clean_key:
        return f"/api/storage/{clean_key}"
    return raw_url or ""



def get_s3_object_stream(s3_key: str, chunk_size: int = 65536) -> tuple:
    """
    Fetches a streaming generator, content_type, and content_length from MinIO S3.
    Returns (generator, content_type, content_length) or (None, None, None).
    Streams chunks on demand without buffering the entire object in memory.
    """
    clean_key = (s3_key or "").lstrip("/")
    if not HAS_BOTO3:
        client = None
    else:
        client = _get_client()

    if client:
        for bucket in [_images_bucket(), _docs_bucket(), _staging_bucket(), _approved_bucket()]:
            try:
                resp = client.get_object(Bucket=bucket, Key=clean_key)
                body = resp.get("Body")
                ctype = resp.get("ContentType", "image/png")
                content_length = resp.get("ContentLength")

                def _stream_iterator():
                    try:
                        for chunk in body.iter_chunks(chunk_size=chunk_size):
                            yield chunk
                    finally:
                        body.close()

                return _stream_iterator(), ctype, content_length
            except Exception as e:
                err_str = str(e)
                if "NoSuchKey" in err_str or "Not Found" in err_str or "404" in err_str:
                    logger.debug(f"S3 object '{clean_key}' not found in bucket '{bucket}': {e}")
                else:
                    logger.warning(f"Failed to fetch S3 object '{clean_key}' from bucket '{bucket}': {e}")

    return None, None, None


def get_s3_object_data(s3_key: str) -> tuple:
    """
    Fetches raw object bytes and content_type from MinIO or fallback local storage.
    Returns (bytes, content_type) or (None, None).
    """
    clean_key = (s3_key or "").lstrip("/")
    if not HAS_BOTO3:
        client = None
    else:
        client = _get_client()

    if client:
        for bucket in [_images_bucket(), _docs_bucket(), _staging_bucket(), _approved_bucket()]:
            try:
                resp = client.get_object(Bucket=bucket, Key=clean_key)
                body = resp["Body"].read()
                ctype = resp.get("ContentType", "image/png")
                return body, ctype
            except Exception as e:
                err_str = str(e)
                if "NoSuchKey" in err_str or "Not Found" in err_str or "404" in err_str:
                    logger.debug(f"S3 object '{clean_key}' not found in bucket '{bucket}': {e}")
                else:
                    logger.warning(f"Failed to fetch S3 object '{clean_key}' from bucket '{bucket}': {e}")

    # Fallback: check local disk storage folders
    fname = os.path.basename(clean_key)
    clean_norm = os.path.normpath(clean_key)
    for folder in ["data/temp", "data/images", "data/uploads", "data/documents", "data/storage"]:
        for candidate in [clean_key, clean_norm, fname]:
            local_path = os.path.normpath(os.path.join(folder, candidate))
            if os.path.exists(local_path) and os.path.isfile(local_path):
                try:
                    with open(local_path, "rb") as f:
                        file_bytes = f.read()
                    ext = os.path.splitext(fname)[1].lower()
                    mime_map = {
                        ".png": "image/png",
                        ".jpg": "image/jpeg",
                        ".jpeg": "image/jpeg",
                        ".webp": "image/webp",
                        ".pdf": "application/pdf",
                        ".json": "application/json"
                    }
                    return file_bytes, mime_map.get(ext, "image/png")
                except Exception:
                    pass

    return None, None


# ─── IMAGE STORAGE (bucket: images) ──────────────────────────────────────────

def upload_image(content: bytes, filename: str, content_type: str = "image/png") -> dict:
    """
    Synchronously uploads image binary content to images bucket (PUBLIC-READ).
    Falls back cleanly to local disk storage ONLY if MinIO is unavailable.
    """
    clean_filename = re.sub(r'[^a-zA-Z0-9._-]', '_', str(filename or "image.png"))
    clean_filename = re.sub(r'_+', '_', clean_filename)
    s3_key = f"images/{uuid.uuid4().hex}_{clean_filename}"
    browser_url = _format_browser_url(None, s3_key)
    bucket_name = _images_bucket()

    client = _get_client()
    if not client:
        _save_file_to_local_disk(content, filename, s3_key=s3_key)
        return {
            "s3_key": s3_key,
            "image_url": browser_url,
            "size": len(content),
            "status": "fallback"
        }

    try:
        extra_args = {}
        if content_type:
            extra_args["ContentType"] = content_type

        client.put_object(
            Bucket=bucket_name,
            Key=s3_key,
            Body=content,
            **extra_args
        )

        logger.debug(f"✅ Successfully uploaded image '{filename}' to MinIO -> {browser_url}")
        return {
            "s3_key": s3_key,
            "image_url": browser_url,
            "size": len(content),
            "status": "success"
        }
    except Exception as e:
        logger.warning(f"MinIO upload error for '{filename}': {e}. Falling back to local disk.")
        _save_file_to_local_disk(content, filename, s3_key=s3_key)
        return {
            "s3_key": s3_key,
            "image_url": browser_url,
            "size": len(content),
            "status": "fallback"
        }


def upload_images_parallel(images: list) -> list:
    """
    Upload multiple images to MinIO concurrently using ThreadPoolExecutor.
    Falls back cleanly to local disk storage ONLY if MinIO is offline.
    """
    if not images:
        return []

    client = _get_client()
    bucket_name = _images_bucket() if client else None

    if not client:
        results = []
        for img in images:
            s3_key = f"images/{uuid.uuid4().hex}_{img['filename']}"
            if img.get("content") and img.get("filename"):
                _save_file_to_local_disk(img["content"], img["filename"], s3_key=s3_key)
            results.append({
                "s3_key": s3_key,
                "image_url": _format_browser_url(None, s3_key),
                "size": len(img.get("content", b"")),
                "status": "fallback"
            })
        return results

    def _upload_single(img_data: dict) -> dict:
        fname = img_data["filename"]
        content = img_data["content"]
        ctype = img_data.get("content_type", "image/png")
        s3_key = f"images/{uuid.uuid4().hex}_{fname}"
        browser_url = _format_browser_url(None, s3_key)
        try:
            extra_args = {}
            if ctype:
                extra_args["ContentType"] = ctype
            client.put_object(
                Bucket=bucket_name,
                Key=s3_key,
                Body=content,
                **extra_args
            )
            logger.debug(f"Uploaded '{fname}' to MinIO -> {browser_url}")
            return {
                "s3_key": s3_key,
                "image_url": browser_url,
                "size": len(content),
                "status": "success"
            }
        except Exception as e:
            logger.warning(f"MinIO upload failed for '{fname}': {e}. Falling back to local disk.")
            _save_file_to_local_disk(content, fname, s3_key=s3_key)
            return {
                "s3_key": s3_key,
                "image_url": browser_url,
                "size": len(content),
                "status": "fallback"
            }

    from concurrent.futures import ThreadPoolExecutor
    with ThreadPoolExecutor(max_workers=min(len(images), 8)) as executor:
        results = list(executor.map(_upload_single, images))

    success_count = sum(1 for r in results if r["status"] == "success")
    logger.info(f"Parallel upload complete: {success_count}/{len(images)} images uploaded successfully.")
    return results


def get_presigned_url(s3_key: str, expires: int = 604800) -> str:
    """Generates presigned GET URL for an existing image object key (7 day default)."""
    clean_key = (s3_key or "").lstrip("/")
    try:
        raw_url = _generate_presigned_url(_images_bucket(), clean_key, expires)
        return _format_browser_url(raw_url, clean_key)
    except Exception as e:
        logger.warning(f"Failed to generate presigned URL for key '{clean_key}': {e}")
        return _format_browser_url(None, clean_key)


def delete_image(s3_key: str) -> None:
    """Deletes an image object from images bucket."""
    client = _get_client()
    if not client:
        return
    try:
        client.delete_object(Bucket=_images_bucket(), Key=s3_key)
        logger.info(f"Deleted image key '{s3_key}' from MinIO")
    except Exception as e:
        logger.debug(f"Failed to delete image key '{s3_key}' from MinIO: {e}")


def replace_image(old_s3_key_or_url: str, new_content: bytes, new_filename: str, content_type: str = "image/png") -> dict:
    """
    Replaces an existing image asset with new binary content.
    Deletes old S3 key if present and uploads new image.
    """
    clean_old_key = (old_s3_key_or_url or "").strip()
    if clean_old_key.startswith("/api/storage/"):
        clean_old_key = clean_old_key.replace("/api/storage/", "")
    elif "images/" in clean_old_key:
        clean_old_key = "images/" + clean_old_key.split("images/")[-1]

    if clean_old_key:
        try:
            delete_image(clean_old_key)
        except Exception as del_err:
            logger.debug(f"Could not delete old image asset '{clean_old_key}': {del_err}")

    return upload_image(new_content, new_filename, content_type=content_type)



# ─── DOCUMENT STORAGE (bucket: knowledge-documents) ──────────────────────────
# Original uploaded files and canonical JSON are stored here.
# Key pattern: originals/{year}/{month}/{document-id}/original.{ext}
#              canonical/{document-id}/document.json

def _build_document_s3_key(document_id: str, filename: str) -> str:
    """
    Builds the S3 key for an original document upload.
    Pattern: originals/{year}/{month}/{document-id}/original.{ext}
    """
    now = datetime.utcnow()
    ext = os.path.splitext(filename)[1].lower() if filename else ""
    return f"originals/{now.year}/{now.month:02d}/{document_id}/original{ext}"


def _build_canonical_s3_key(document_id: str) -> str:
    """
    Builds the S3 key for canonical JSON.
    Pattern: canonical/{document-id}/document.json
    """
    return f"canonical/{document_id}/document.json"


def upload_document(
    content: bytes,
    filename: str,
    document_id: str,
    content_type: str = "application/octet-stream"
) -> dict:
    """
    Uploads original document file to knowledge-documents bucket.
    Falls back cleanly to local disk storage if MinIO is offline.
    """
    s3_key = _build_document_s3_key(document_id, filename)
    bucket_name = _docs_bucket()

    client = _get_client()
    if not client:
        _save_file_to_local_disk(content, filename, s3_key=s3_key)
        return {
            "s3_key": s3_key,
            "bucket": bucket_name,
            "document_url": _format_browser_url(None, s3_key),
            "size": len(content),
            "status": "fallback"
        }

    try:
        extra_args = {}
        if content_type:
            extra_args["ContentType"] = content_type

        client.put_object(
            Bucket=bucket_name,
            Key=s3_key,
            Body=content,
            **extra_args
        )

        doc_url = _generate_presigned_url(bucket_name, s3_key, expires=3600)

        logger.info(f"📄 Uploaded original document '{filename}' -> {bucket_name}/{s3_key}")
        return {
            "s3_key": s3_key,
            "bucket": bucket_name,
            "document_url": doc_url,
            "size": len(content),
            "status": "success"
        }
    except Exception as e:
        logger.warning(f"Document upload to MinIO failed for '{filename}': {e}. Falling back to local disk.")
        _save_file_to_local_disk(content, filename, s3_key=s3_key)
        return {
            "s3_key": s3_key,
            "bucket": bucket_name,
            "document_url": _format_browser_url(None, s3_key),
            "size": len(content),
            "status": "fallback"
        }


def upload_canonical_json(document_id: str, canonical_data: dict) -> dict:
    """
    Uploads canonical JSON (approved document state) to knowledge-documents bucket.
    Key: canonical/{document-id}/document.json
    """
    s3_key = _build_canonical_s3_key(document_id)
    bucket_name = _docs_bucket()

    # Save to local disk output folder
    try:
        os.makedirs("data/output", exist_ok=True)
        with open(f"data/output/{document_id}.json", "w", encoding="utf-8") as f:
            json.dump(canonical_data, f, indent=2, ensure_ascii=False)
    except Exception:
        pass

    client = _get_client()
    if not client:
        return {"s3_key": s3_key, "bucket": bucket_name, "status": "fallback"}

    try:
        json_bytes = json.dumps(canonical_data, indent=2, ensure_ascii=False).encode("utf-8")
        client.put_object(
            Bucket=bucket_name,
            Key=s3_key,
            Body=json_bytes,
            ContentType="application/json"
        )

        logger.info(f"📋 Uploaded canonical JSON for '{document_id}' -> {bucket_name}/{s3_key}")
        return {"s3_key": s3_key, "bucket": bucket_name, "status": "success"}
    except Exception as e:
        logger.debug(f"Canonical JSON upload note for '{document_id}': {e}")
        return {"s3_key": s3_key, "bucket": bucket_name, "status": "fallback"}


# ─── STAGING & APPROVED JSON STORAGE (buckets: staging, approved) ────────────

def upload_staging_json(knowledge_id: str, data: dict) -> dict:
    """
    Uploads staging JSON to MinIO bucket 'staging' as source of truth.
    Mirrors to local disk cache 'data/pending/{knowledge_id}.json'.
    """
    s3_key = f"{knowledge_id}.json"
    bucket_name = _staging_bucket()

    # Mirror to local disk cache
    try:
        os.makedirs("data/pending", exist_ok=True)
        local_path = os.path.join("data/pending", s3_key)
        with open(local_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
    except Exception as e:
        logger.debug(f"Local staging cache write note: {e}")

    client = _get_client()
    if not client:
        return {"s3_key": s3_key, "bucket": bucket_name, "status": "fallback"}

    try:
        json_bytes = json.dumps(data, indent=2, ensure_ascii=False).encode("utf-8")
        client.put_object(
            Bucket=bucket_name,
            Key=s3_key,
            Body=json_bytes,
            ContentType="application/json"
        )
        logger.info(f"📥 Uploaded staging JSON for '{knowledge_id}' -> {bucket_name}/{s3_key}")
        return {"s3_key": s3_key, "bucket": bucket_name, "status": "success"}
    except Exception as e:
        logger.debug(f"Staging JSON upload note for '{knowledge_id}': {e}")
        return {"s3_key": s3_key, "bucket": bucket_name, "status": "fallback"}


def get_staging_json(knowledge_id: str) -> Optional[dict]:
    """
    Retrieves staging JSON from MinIO 'staging' bucket (source of truth).
    If found in MinIO, updates/refreshes local disk cache in 'data/pending/{knowledge_id}.json'.
    Falls back to local disk if MinIO is offline or object not found in MinIO.
    """
    s3_key = f"{knowledge_id}.json"
    bucket_name = _staging_bucket()
    client = _get_client()

    if client:
        try:
            resp = client.get_object(Bucket=bucket_name, Key=s3_key)
            raw = resp["Body"].read().decode("utf-8")
            data = json.loads(raw)
            # Update local disk cache
            try:
                os.makedirs("data/pending", exist_ok=True)
                with open(os.path.join("data/pending", s3_key), "w", encoding="utf-8") as f:
                    f.write(raw)
            except Exception:
                pass
            return data
        except Exception:
            pass

    # Fallback to local disk cache
    for candidate in [
        os.path.join("data/pending", f"{knowledge_id}.json"),
        os.path.join("data/pending", f"{knowledge_id}_parsed.json"),
    ]:
        if os.path.exists(candidate):
            try:
                with open(candidate, "r", encoding="utf-8") as f:
                    return json.load(f)
            except Exception:
                pass

    return None


def upload_approved_json(knowledge_id: str, data: dict) -> dict:
    """
    Uploads approved JSON to MinIO bucket 'approved' as source of truth.
    Mirrors to local disk cache 'data/output/{knowledge_id}.json'.
    Also maintains backward compatibility with canonical JSON in docs bucket.
    """
    s3_key = f"{knowledge_id}.json"
    bucket_name = _approved_bucket()

    # Mirror to local disk cache
    try:
        os.makedirs("data/output", exist_ok=True)
        local_path = os.path.join("data/output", s3_key)
        with open(local_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
    except Exception as e:
        logger.debug(f"Local approved cache write note: {e}")

    client = _get_client()
    if not client:
        return {"s3_key": s3_key, "bucket": bucket_name, "status": "fallback"}

    try:
        json_bytes = json.dumps(data, indent=2, ensure_ascii=False).encode("utf-8")
        client.put_object(
            Bucket=bucket_name,
            Key=s3_key,
            Body=json_bytes,
            ContentType="application/json"
        )
        logger.info(f"✅ Uploaded approved JSON for '{knowledge_id}' -> {bucket_name}/{s3_key}")
        # Maintain canonical JSON in knowledge-documents for backward compatibility
        try:
            upload_canonical_json(knowledge_id, data)
        except Exception:
            pass
        return {"s3_key": s3_key, "bucket": bucket_name, "status": "success"}
    except Exception as e:
        logger.debug(f"Approved JSON upload note for '{knowledge_id}': {e}")
        return {"s3_key": s3_key, "bucket": bucket_name, "status": "fallback"}


def get_approved_json(knowledge_id: str) -> Optional[dict]:
    """
    Retrieves approved JSON from MinIO 'approved' bucket (source of truth).
    If found in MinIO, updates/refreshes local disk cache in 'data/output/{knowledge_id}.json'.
    Falls back to local disk if MinIO is offline.
    """
    s3_key = f"{knowledge_id}.json"
    bucket_name = _approved_bucket()
    client = _get_client()

    if client:
        try:
            resp = client.get_object(Bucket=bucket_name, Key=s3_key)
            raw = resp["Body"].read().decode("utf-8")
            data = json.loads(raw)
            # Update local disk cache
            try:
                os.makedirs("data/output", exist_ok=True)
                with open(os.path.join("data/output", s3_key), "w", encoding="utf-8") as f:
                    f.write(raw)
            except Exception:
                pass
            return data
        except Exception:
            pass

    # Fallback to local disk cache
    for candidate in [
        os.path.join("data/output", f"{knowledge_id}.json"),
        os.path.join("data/output", f"{knowledge_id}_parsed.json"),
    ]:
        if os.path.exists(candidate):
            try:
                with open(candidate, "r", encoding="utf-8") as f:
                    return json.load(f)
            except Exception:
                pass

    return None


def promote_staging_to_approved(knowledge_id: str, data: dict) -> dict:
    """
    Promotes document from staging to approved:
    1. Uploads to MinIO 'approved' bucket and writes 'data/output/{knowledge_id}.json'.
    2. Deletes from MinIO 'staging' bucket and deletes 'data/pending/{knowledge_id}.json'.
    """
    res = upload_approved_json(knowledge_id, data)
    delete_staging_json(knowledge_id)
    return res


def delete_staging_json(knowledge_id: str) -> None:
    """Deletes staging JSON from MinIO 'staging' bucket and local pending cache."""
    client = _get_client()
    bucket = _staging_bucket()
    if client:
        for s3_k in [f"{knowledge_id}.json", f"{knowledge_id}_parsed.json"]:
            try:
                client.delete_object(Bucket=bucket, Key=s3_k)
                logger.info(f"Deleted staging JSON '{s3_k}' from MinIO '{bucket}'")
            except Exception as e:
                logger.debug(f"Failed to delete staging JSON from MinIO: {e}")
        try:
            paginator = client.get_paginator('list_objects_v2')
            for page in paginator.paginate(Bucket=bucket, Prefix=str(knowledge_id)):
                for obj in page.get('Contents', []):
                    try:
                        client.delete_object(Bucket=bucket, Key=obj['Key'])
                        logger.info(f"Deleted staging object '{obj['Key']}' from MinIO '{bucket}'")
                    except Exception:
                        pass
        except Exception:
            pass

    # Remove local cache files across all potential folders
    for folder in ["data/pending", "data/temp", "data/storage"]:
        for name in [f"{knowledge_id}.json", f"{knowledge_id}_parsed.json"]:
            path = os.path.join(folder, name)
            if os.path.exists(path):
                try:
                    os.remove(path)
                except Exception:
                    pass


def delete_approved_json(knowledge_id: str) -> None:
    """Deletes approved JSON from MinIO 'approved' bucket and local output cache."""
    client = _get_client()
    bucket = _approved_bucket()
    if client:
        for s3_k in [f"{knowledge_id}.json", f"{knowledge_id}_parsed.json"]:
            try:
                client.delete_object(Bucket=bucket, Key=s3_k)
                logger.info(f"Deleted approved JSON '{s3_k}' from MinIO '{bucket}'")
            except Exception as e:
                logger.debug(f"Failed to delete approved JSON from MinIO: {e}")
        try:
            paginator = client.get_paginator('list_objects_v2')
            for page in paginator.paginate(Bucket=bucket, Prefix=str(knowledge_id)):
                for obj in page.get('Contents', []):
                    try:
                        client.delete_object(Bucket=bucket, Key=obj['Key'])
                        logger.info(f"Deleted approved object '{obj['Key']}' from MinIO '{bucket}'")
                    except Exception:
                        pass
        except Exception:
            pass

    # Remove local cache files across all potential folders
    for folder in ["data/output", "data/approved", "data/temp", "data/storage"]:
        for name in [f"{knowledge_id}.json", f"{knowledge_id}_parsed.json"]:
            path = os.path.join(folder, name)
            if os.path.exists(path):
                try:
                    os.remove(path)
                except Exception:
                    pass


def sync_existing_local_to_minio(client=None) -> dict:
    """
    Syncs any local files created while MinIO was offline back into MinIO:
    1. Uploads files from 'data/pending' to MinIO 'staging' bucket.
    2. Uploads files from 'data/output' to MinIO 'approved' bucket.
    3. Uploads binary files from 'data/storage' to MinIO 'images' or 'knowledge-documents' buckets,
       and automatically DELETES them from 'data/storage' upon successful upload so local disk remains 100% clean.
    """
    synced_staging = 0
    synced_approved = 0
    synced_storage = 0
    if client is None:
        client = _get_client()
    if not client:
        return {"staging": 0, "approved": 0, "storage": 0, "status": "offline"}

    staging_bucket = _staging_bucket()
    approved_bucket = _approved_bucket()
    images_bucket = _images_bucket()
    docs_bucket = _docs_bucket()

    # 1. Sync data/pending -> staging
    if os.path.exists("data/pending"):
        for fname in os.listdir("data/pending"):
            if fname.endswith(".json") and not fname.endswith("_history.json"):
                kid = fname[:-5].replace("_parsed", "")
                full_path = os.path.join("data/pending", fname)
                try:
                    with open(full_path, "r", encoding="utf-8") as f:
                        data = json.load(f)
                    json_bytes = json.dumps(data, indent=2, ensure_ascii=False).encode("utf-8")
                    client.put_object(
                        Bucket=staging_bucket,
                        Key=f"{kid}.json",
                        Body=json_bytes,
                        ContentType="application/json"
                    )
                    synced_staging += 1
                except Exception as e:
                    logger.debug(f"Sync pending file '{fname}' note: {e}")

    # 2. Sync data/output -> approved
    if os.path.exists("data/output"):
        for fname in os.listdir("data/output"):
            if fname.endswith(".json") and not fname.endswith("_history.json"):
                kid = fname[:-5].replace("_parsed", "")
                full_path = os.path.join("data/output", fname)
                try:
                    with open(full_path, "r", encoding="utf-8") as f:
                        data = json.load(f)
                    json_bytes = json.dumps(data, indent=2, ensure_ascii=False).encode("utf-8")
                    client.put_object(
                        Bucket=approved_bucket,
                        Key=f"{kid}.json",
                        Body=json_bytes,
                        ContentType="application/json"
                    )
                    synced_approved += 1
                except Exception as e:
                    logger.debug(f"Sync approved file '{fname}' note: {e}")

    # 3. Sync and flush data/storage -> MinIO images & documents, then delete from local disk!
    if os.path.exists("data/storage"):
        for root, _, files in os.walk("data/storage"):
            for fname in files:
                full_path = os.path.join(root, fname)
                ext = os.path.splitext(fname)[1].lower()
                try:
                    with open(full_path, "rb") as f:
                        file_bytes = f.read()

                    if not file_bytes:
                        try:
                            os.remove(full_path)
                        except Exception:
                            pass
                        continue

                    # Determine target bucket & S3 key
                    if ext in [".png", ".jpg", ".jpeg", ".webp", ".gif", ".svg"]:
                        target_bucket = images_bucket
                        target_key = f"images/{fname}" if not fname.startswith("images/") else fname
                        content_type = f"image/{ext.lstrip('.')}" if ext != ".jpg" else "image/jpeg"
                    else:
                        target_bucket = docs_bucket
                        target_key = f"originals/fallback/{fname}"
                        content_type = "application/octet-stream"

                    client.put_object(
                        Bucket=target_bucket,
                        Key=target_key,
                        Body=file_bytes,
                        ContentType=content_type
                    )
                    synced_storage += 1

                    # Remove from local disk after successful upload!
                    try:
                        os.remove(full_path)
                        logger.info(f"🔄 Migrated fallback file '{fname}' to MinIO '{target_bucket}/{target_key}' and removed from local disk.")
                    except Exception as rm_e:
                        logger.debug(f"Could not remove synced fallback file {full_path}: {rm_e}")
                except Exception as upload_e:
                    logger.warning(f"Failed to sync fallback file '{fname}' to MinIO: {upload_e}")

    if synced_staging > 0 or synced_approved > 0 or synced_storage > 0:
        logger.info(f"🔄 Synced local files to MinIO: {synced_staging} staging, {synced_approved} approved, {synced_storage} storage migrated.")
    return {"staging": synced_staging, "approved": synced_approved, "storage": synced_storage, "status": "success"}


def get_document_presigned_url(s3_key: str, expires: int = 3600) -> str:
    """Generates presigned GET URL for a document (1 hour default — shorter for security)."""
    return _generate_presigned_url(_docs_bucket(), s3_key, expires)


def delete_document_file(s3_key: str) -> None:
    """Deletes a document object from knowledge-documents bucket."""
    client = _get_client()
    if not client:
        return
    try:
        client.delete_object(Bucket=_docs_bucket(), Key=s3_key)
        logger.info(f"Deleted document key '{s3_key}' from MinIO")
    except Exception as e:
        logger.debug(f"Failed to delete document key '{s3_key}' from MinIO: {e}")


def clear_all_buckets() -> dict:
    """
    Deletes ALL objects across ALL buckets in MinIO.
    Re-initializes required buckets ('images', 'knowledge-documents', 'staging', 'approved') and policies afterwards.
    """
    if not HAS_BOTO3:
        return {"status": "skipped", "reason": "boto3 not installed"}

    deleted_counts = {}
    global _cached_client
    try:
        client = _get_client()
        if not client:
            logger.info("MinIO is offline; clear_all_buckets operating in local disk fallback mode.")
            return {"status": "success", "deleted_counts": {}, "mode": "local_fallback"}

        # Scan ALL buckets currently in MinIO
        all_b_res = client.list_buckets()
        bucket_names = [b["Name"] for b in all_b_res.get("Buckets", [])]

        # Always include active configured buckets
        for target_b in [_images_bucket(), _docs_bucket(), _staging_bucket(), _approved_bucket(), "images", "knowledge-documents", "staging", "approved"]:
            if target_b not in bucket_names:
                bucket_names.append(target_b)

        for bucket_name in set(bucket_names):
            count = 0
            try:
                paginator = client.get_paginator('list_objects_v2')
                for page in paginator.paginate(Bucket=bucket_name):
                    objects = page.get('Contents', [])
                    for obj in objects:
                        try:
                            client.delete_object(Bucket=bucket_name, Key=obj['Key'])
                            count += 1
                        except Exception as del_err:
                            logger.warning(f"Error deleting object '{obj['Key']}' from bucket '{bucket_name}': {del_err}")
                deleted_counts[bucket_name] = count
                logger.info(f"🗑️ Cleared {count} objects from MinIO bucket '{bucket_name}'.")
            except Exception as b_err:
                logger.warning(f"Error clearing MinIO bucket '{bucket_name}': {b_err}")
                deleted_counts[bucket_name] = count

        ensure_all_buckets()
        return {"status": "success", "deleted_counts": deleted_counts}
    except Exception as e:
        logger.error(f"clear_all_buckets failed: {e}")
        _cached_client = None  # Reset client cache so next attempt re-evaluates endpoint connectivity
        return {"status": "error", "message": str(e)}


def delete_image_by_ref(raw_ref: str, knowledge_id: Optional[str] = None) -> bool:
    """
    Sanitizes and deletes a single image reference from MinIO images bucket
    and local disk fallback storage.
    """
    if not raw_ref or not isinstance(raw_ref, str):
        return False
    clean = raw_ref.strip()
    client = _get_client()
    images_bucket = _images_bucket()

    # Strip URL prefix if present
    if "/api/storage/" in clean:
        clean = clean.split("/api/storage/")[-1]
    elif "/storage/" in clean:
        clean = clean.split("/storage/")[-1]
    elif "://" in clean:
        from urllib.parse import urlparse
        clean = urlparse(clean).path.lstrip("/")
        if clean.startswith(f"{images_bucket}/"):
            clean = clean[len(images_bucket) + 1:]

    clean = clean.lstrip("/")
    fname = os.path.basename(clean)

    if not fname or len(fname) < 4:
        return False

    success = False
    # Delete from MinIO images bucket
    if client:
        for s3_candidate in [f"images/{fname}", clean, fname]:
            try:
                client.delete_object(Bucket=images_bucket, Key=s3_candidate)
                success = True
            except Exception as e:
                logger.debug(f"MinIO delete image '{s3_candidate}' note: {e}")
        log_kid = f" for doc '{knowledge_id}'" if knowledge_id else ""
        logger.info(f"🗑️ Deleted MinIO image '{fname}'{log_kid}")

    # Delete from local disk fallback storage
    for folder in ["data/images", "data/storage/images", "data/temp", "data/uploads", "data/storage"]:
        for candidate in [fname, f"images/{fname}"]:
            local_f = os.path.normpath(os.path.join(folder, candidate))
            if os.path.exists(local_f) and os.path.isfile(local_f):
                try:
                    os.remove(local_f)
                    logger.debug(f"Removed local disk fallback image: {local_f}")
                except Exception:
                    pass

    return success


def extract_image_keys_from_doc_data(doc_data: dict) -> set:
    """
    Exhaustively extracts all image filenames and S3 keys referenced in a document dictionary.
    Scans:
    1. Direct image_url, image_urls, all_extracted_images
    2. Metadata (images, image_urls, all_extracted_images, initial_summary, s3_key)
    3. Summaries: summary, initial_summary, batch_summary
    4. Histories: history, staging_history, chat_history, edit_history (content & attachments)
    5. Chunks text & chunk metadata
    6. Complete regex scanner across the entire JSON-serialized doc_data
    """
    if not isinstance(doc_data, dict):
        return set()

    found_keys = set()
    
    # 1. Direct image_urls list & image_url
    if doc_data.get("image_url") and isinstance(doc_data["image_url"], str):
        found_keys.add(doc_data["image_url"].strip())
    for u in doc_data.get("image_urls", []) or []:
        if isinstance(u, str) and u.strip():
            found_keys.add(u.strip())
    for u in doc_data.get("all_extracted_images", []) or []:
        if isinstance(u, str) and u.strip():
            found_keys.add(u.strip())
            
    # 2. Metadata images / image_urls / all_extracted_images
    meta = doc_data.get("metadata", {})
    if isinstance(meta, dict):
        for k in ["image_urls", "all_extracted_images"]:
            for u in meta.get(k, []) or []:
                if isinstance(u, str) and u.strip():
                    found_keys.add(u.strip())
        for img in meta.get("images", []) or []:
            if isinstance(img, dict):
                u = img.get("url") or img.get("image_url") or img.get("s3_key")
                if u and isinstance(u, str):
                    found_keys.add(u.strip())
            elif isinstance(img, str) and img.strip():
                found_keys.add(img.strip())
        if meta.get("s3_key"):
            found_keys.add(str(meta["s3_key"]).strip())
        if meta.get("image_url") and isinstance(meta["image_url"], str):
            found_keys.add(meta["image_url"].strip())

    # 3. Summaries (summary, initial_summary, batch_summary)
    for sum_key in ["summary", "initial_summary", "batch_summary"]:
        for container in [doc_data, meta if isinstance(meta, dict) else {}]:
            s_val = str(container.get(sum_key, "") or "")
            if s_val:
                for m in re.findall(r'!\[.*?\]\(([^)\s]+)\)', s_val):
                    if m and isinstance(m, str):
                        found_keys.add(m.strip())

    # 4. Histories (history, staging_history, chat_history, edit_history)
    for hist_key in ["history", "staging_history", "chat_history", "edit_history"]:
        for container in [doc_data, meta if isinstance(meta, dict) else {}]:
            h_list = container.get(hist_key) or []
            if isinstance(h_list, list):
                for turn in h_list:
                    if isinstance(turn, dict):
                        c_text = str(turn.get("content", "") or "")
                        if c_text:
                            for m in re.findall(r'!\[.*?\]\(([^)\s]+)\)', c_text):
                                if m and isinstance(m, str):
                                    found_keys.add(m.strip())
                        # Check attachments in turn
                        for att_k in ["attachmentName", "attachmentNames", "images", "image_urls"]:
                            att_v = turn.get(att_k)
                            if isinstance(att_v, list):
                                for a in att_v:
                                    if isinstance(a, str) and a.strip():
                                        found_keys.add(a.strip())
                            elif isinstance(att_v, str) and att_v.strip():
                                found_keys.add(att_v.strip())

    # 5. Chunks text & metadata
    for chunk in doc_data.get("chunks", []) or []:
        if not isinstance(chunk, dict):
            continue
        c_text = str(chunk.get("text", "") or "")
        if c_text:
            for m in re.findall(r'!\[.*?\]\(([^)\s]+)\)', c_text):
                if m and isinstance(m, str):
                    found_keys.add(m.strip())
        c_meta = chunk.get("metadata", {})
        if isinstance(c_meta, dict):
            for k in ["image_url", "image_urls", "s3_key", "image_reference"]:
                val = c_meta.get(k)
                if isinstance(val, list):
                    for v in val:
                        if isinstance(v, str) and v.strip():
                            found_keys.add(v.strip())
                elif isinstance(val, str) and val.strip():
                    found_keys.add(val.strip())

    # 6. Global regex scan across serialized JSON representation of doc_data
    try:
        raw_json = json.dumps(doc_data)
        for m in re.findall(r'!\[.*?\]\(([^)\s]+)\)', raw_json):
            if m:
                found_keys.add(m.strip())
        for m in re.findall(r'/(?:api/)?storage/images/[a-zA-Z0-9_\-\.]+', raw_json):
            if m:
                found_keys.add(m.strip())
        for m in re.findall(r'\bimages/[a-zA-Z0-9_\-\.]+\.(?:png|jpe?g|webp|gif|bmp)\b', raw_json, re.IGNORECASE):
            if m:
                found_keys.add(m.strip())
        for m in re.findall(r'\b[a-fA-F0-9]{32}_[a-zA-Z0-9_\-\.]+\.(?:png|jpe?g|webp|gif|bmp)\b', raw_json, re.IGNORECASE):
            if m:
                found_keys.add(m.strip())
    except Exception as scan_err:
        logger.debug(f"JSON regex scan note: {scan_err}")

    return found_keys


def delete_knowledge_images_and_assets(knowledge_id: str, doc_data: Optional[dict] = None) -> dict:
    """
    Comprehensively deletes all MinIO objects and local fallback files associated with a knowledge document:
    1. All embedded images in MinIO 'images' bucket.
    2. All original documents and canonical JSON in MinIO 'knowledge-documents' bucket.
    3. Staging and approved JSONs in MinIO 'staging' and 'approved' buckets.
    4. Local disk fallback files in data/images, data/storage, data/temp, data/uploads.
    """
    kid_str = str(knowledge_id).strip()
    client = _get_client()
    docs_bucket = _docs_bucket()

    all_image_refs = set()
    if doc_data and isinstance(doc_data, dict):
        all_image_refs.update(extract_image_keys_from_doc_data(doc_data))

    # Also check staging and approved JSON from MinIO or disk if doc_data wasn't fully populated
    for getter in [get_staging_json, get_approved_json]:
        try:
            m_doc = getter(kid_str)
            if m_doc and isinstance(m_doc, dict):
                all_image_refs.update(extract_image_keys_from_doc_data(m_doc))
        except Exception:
            pass

    # Check local JSON cache if doc_data wasn't fully populated
    for folder in ["data/output", "data/pending", "data/temp"]:
        for cand in [f"{kid_str}.json", f"{kid_str}_parsed.json"]:
            cand_path = os.path.join(folder, cand)
            if os.path.exists(cand_path):
                try:
                    with open(cand_path, "r", encoding="utf-8") as fp:
                        cached_doc = json.load(fp)
                    if isinstance(cached_doc, dict):
                        all_image_refs.update(extract_image_keys_from_doc_data(cached_doc))
                except Exception:
                    pass

    deleted_images = []
    for ref in all_image_refs:
        if delete_image_by_ref(ref, knowledge_id=kid_str):
            deleted_images.append(os.path.basename(ref))

    # Clean MinIO knowledge-documents bucket (originals & canonical)
    if client and kid_str:
        try:
            # 1. Delete canonical JSON
            client.delete_object(Bucket=docs_bucket, Key=f"canonical/{kid_str}/document.json")
        except Exception:
            pass

        try:
            # 2. Delete original upload files in originals/.../{kid_str}/...
            paginator = client.get_paginator('list_objects_v2')
            for page in paginator.paginate(Bucket=docs_bucket, Prefix="originals/"):
                for obj in page.get('Contents', []):
                    key = obj.get('Key', '')
                    if f"/{kid_str}/" in key:
                        try:
                            client.delete_object(Bucket=docs_bucket, Key=key)
                            logger.info(f"🗑️ Deleted original document '{key}' from MinIO '{docs_bucket}'")
                        except Exception as err:
                            logger.debug(f"Could not delete original document '{key}': {err}")
        except Exception as e:
            logger.debug(f"Error purging originals for '{kid_str}': {e}")

    # Clean staging & approved JSON in MinIO
    try:
        delete_staging_json(kid_str)
        delete_approved_json(kid_str)
    except Exception:
        pass

    return {
        "knowledge_id": kid_str,
        "deleted_images_count": len(set(deleted_images)),
        "deleted_images": list(set(deleted_images))
    }



