"""S3-compatible dual-bucket object storage via boto3 (MinIO, AWS S3, etc.).

Bucket architecture:
  images                → embedded images from documents (private, presigned URL access)
  knowledge-documents   → original uploaded documents + canonical JSON (private, presigned URL access)

Both buckets are PRIVATE. All access goes through presigned URLs generated by the application API.
"""
import os
import time
import json
import uuid
from datetime import datetime
from typing import Optional
from loguru import logger
from app.core.config import settings

try:
    import boto3
    from botocore.config import Config
    HAS_BOTO3 = True
except ImportError:
    boto3 = None
    Config = None
    HAS_BOTO3 = False


# ─── Bucket Names ─────────────────────────────────────────────────────────────

def _images_bucket() -> str:
    """Bucket for embedded images extracted from documents."""
    return os.getenv("S3_BUCKET") or settings.S3_BUCKET or "images"


def _docs_bucket() -> str:
    """Bucket for original uploaded documents and canonical JSON."""
    return os.getenv("S3_DOCUMENTS_BUCKET") or settings.S3_DOCUMENTS_BUCKET or "knowledge-documents"


def _staging_bucket() -> str:
    """Bucket for staging/pending JSON documents under review."""
    return os.getenv("S3_STAGING_BUCKET") or getattr(settings, "S3_STAGING_BUCKET", "staging") or "staging"


def _approved_bucket() -> str:
    """Bucket for approved/published canonical JSON documents."""
    return os.getenv("S3_APPROVED_BUCKET") or getattr(settings, "S3_APPROVED_BUCKET", "approved") or "approved"


# ─── S3 Client ─────────────────────────────────────────────────────────────────

_cached_client = None
_last_client_check_time = 0

def _save_file_to_local_disk(content: bytes, filename: str, s3_key: str = None) -> None:
    """Saves binary content to local disk fallback directory under both basename and s3_key subpaths."""
    if not content:
        return
    targets = [filename]
    if s3_key:
        targets.append(s3_key)
    try:
        for folder in ["data/temp", "data/images", "data/uploads", "data/storage"]:
            for target in targets:
                if not target:
                    continue
                clean_target = os.path.normpath(target.lstrip("/\\"))
                local_path = os.path.normpath(os.path.join(folder, clean_target))
                os.makedirs(os.path.dirname(local_path), exist_ok=True)
                with open(local_path, "wb") as f:
                    f.write(content)
                base_path = os.path.normpath(os.path.join(folder, os.path.basename(clean_target)))
                with open(base_path, "wb") as f:
                    f.write(content)
    except Exception as e:
        logger.debug(f"Local disk fallback write exception for '{filename}': {e}")


def _get_client():
    """
    Creates boto3 S3 client with automatic fallback across docker network (http://minio:9000)
    and host localhost (http://localhost:9000), cached for performance.
    If MinIO/S3 is unreachable, returns None cleanly to enable local storage fallback.
    """
    global _cached_client, _last_client_check_time
    now = time.time()
    if _cached_client is not None:
        return _cached_client if _cached_client is not False else None

    # Don't retry list_buckets continuously if it failed recently (< 30s)
    if now - _last_client_check_time < 30 and _cached_client is False:
        return None

    _last_client_check_time = now

    if not HAS_BOTO3:
        _cached_client = False
        return None

    endpoints = []
    env_endpoint = os.getenv("S3_ENDPOINT_URL") or settings.S3_ENDPOINT_URL
    if env_endpoint:
        endpoints.append(env_endpoint)
    for ep in ["http://minio:9000", "http://localhost:9000", "http://127.0.0.1:9000"]:
        if ep not in endpoints:
            endpoints.append(ep)

    access_key = os.getenv("S3_ACCESS_KEY") or settings.S3_ACCESS_KEY or "minioadmin"
    secret_key = os.getenv("S3_SECRET_KEY") or settings.S3_SECRET_KEY or "minioadmin"
    region = os.getenv("S3_REGION") or settings.S3_REGION or "us-east-1"
    use_path_style = settings.S3_USE_PATH_STYLE if hasattr(settings, "S3_USE_PATH_STYLE") else True

    for endpoint_url in endpoints:
        try:
            client = boto3.client(
                "s3",
                endpoint_url=endpoint_url,
                aws_access_key_id=access_key,
                aws_secret_access_key=secret_key,
                config=Config(
                    signature_version="s3v4",
                    s3={"addressing_style": "path" if use_path_style else "auto"},
                    connect_timeout=0.8,
                    read_timeout=1.5,
                    retries={'max_attempts': 0}
                ),
                region_name=region,
            )
            client.list_buckets()
            _cached_client = client
            return client
        except Exception:
            continue

    _cached_client = False
    logger.info("MinIO S3 service offline or unreachable. Storage operating in seamless local disk mode.")
    return None


# ─── Bucket Initialization ────────────────────────────────────────────────────

def _ensure_bucket_private(bucket_name: str) -> None:
    """Ensures a MinIO bucket exists with PRIVATE access (no public read)."""
    client = _get_client()
    if not client:
        return
    try:
        try:
            client.head_bucket(Bucket=bucket_name)
        except Exception:
            client.create_bucket(Bucket=bucket_name)
            logger.info(f"Created MinIO bucket (private): '{bucket_name}'")
    except Exception as e:
        logger.debug(f"Could not connect or ensure MinIO bucket '{bucket_name}': {e}")


def _ensure_images_bucket() -> None:
    """Ensures images bucket exists with PUBLIC-READ policy so URLs never expire."""
    bucket_name = _images_bucket()
    try:
        client = _get_client()
        try:
            client.head_bucket(Bucket=bucket_name)
        except Exception:
            client.create_bucket(Bucket=bucket_name)
            logger.info(f"Created MinIO bucket: '{bucket_name}'")

        # Set public read policy so browser/frontend can view images directly
        # Images use STATIC URLs that never expire — not presigned URLs
        policy = {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Principal": "*",
                    "Action": ["s3:GetObject"],
                    "Resource": [f"arn:aws:s3:::{bucket_name}/*"]
                }
            ]
        }
        try:
            client.put_bucket_policy(Bucket=bucket_name, Policy=json.dumps(policy))
        except Exception:
            pass
    except Exception as e:
        logger.warning(f"Could not ensure images bucket '{bucket_name}': {e}")


def _ensure_docs_bucket() -> None:
    """Ensures knowledge-documents bucket exists with PRIVATE access."""
    _ensure_bucket_private(_docs_bucket())


def _ensure_staging_bucket() -> None:
    """Ensures staging bucket exists with PRIVATE access."""
    _ensure_bucket_private(_staging_bucket())


def _ensure_approved_bucket() -> None:
    """Ensures approved bucket exists with PRIVATE access."""
    _ensure_bucket_private(_approved_bucket())


def _build_static_image_url(bucket_name: str, s3_key: str) -> str:
    """
    Builds a static (non-expiring) image URL for the public-read images bucket.
    Uses localhost:9000 for browser access (converts docker-internal minio:9000).
    """
    # Always return browser-accessible URL
    return f"http://localhost:9000/{bucket_name}/{s3_key}"


def ensure_all_buckets() -> None:
    """Initialize all 4 buckets at application startup.
    - images: PUBLIC-READ (static URLs, never expire)
    - knowledge-documents: PRIVATE (presigned URLs only)
    - staging: PRIVATE (staged/pending JSON documents)
    - approved: PRIVATE (approved/published canonical JSON documents)
    """
    _ensure_images_bucket()
    _ensure_docs_bucket()
    _ensure_staging_bucket()
    _ensure_approved_bucket()
    logger.info(
        f"MinIO buckets initialized: '{_images_bucket()}' (public-read), "
        f"'{_docs_bucket()}' (private), '{_staging_bucket()}' (private), '{_approved_bucket()}' (private)"
    )
    # Sync any pre-existing local disk pending/output files into MinIO source of truth
    sync_existing_local_to_minio()


# ─── Presigned URL Generation ─────────────────────────────────────────────────

def _generate_presigned_url(bucket_name: str, s3_key: str, expires: int = 604800) -> str:
    """
    Generates presigned GET URL for an S3 object.
    All access is via presigned URLs (both buckets are PRIVATE).
    Default expiry: 7 days for images, callers can override.
    """
    try:
        client = _get_client()
        raw_url = client.generate_presigned_url(
            "get_object",
            Params={"Bucket": bucket_name, "Key": s3_key},
            ExpiresIn=expires
        )
        # Convert docker-internal URL to browser-accessible URL
        if "minio:9000" in raw_url:
            raw_url = raw_url.replace("minio:9000", "localhost:9000")
        return raw_url
    except Exception as e:
        logger.warning(f"Failed to generate presigned URL for '{bucket_name}/{s3_key}': {e}")
        return f"http://localhost:9000/{bucket_name}/{s3_key}"


def _format_browser_url(raw_url: str = None, s3_key: str = "") -> str:
    """
    Ensures image URL is accessible by the user's browser across all environments:
    1. If S3_PUBLIC_URL is configured (e.g. 'https://dokterpedia.aryanoble.co.id/api/storage' or CDN), use that.
    2. Otherwise, returns universal relative backend proxy path '/api/storage/{s3_key}'.
    """
    clean_key = (s3_key or "").lstrip("/")
    if hasattr(settings, "S3_PUBLIC_URL") and settings.S3_PUBLIC_URL and str(settings.S3_PUBLIC_URL).strip():
        base = str(settings.S3_PUBLIC_URL).rstrip("/")
        return f"{base}/{clean_key}"
    
    # Universal fallback proxy path via FastAPI
    return f"/api/storage/{clean_key}"


def get_s3_object_data(s3_key: str) -> tuple:
    """
    Fetches raw object bytes and content_type from MinIO or fallback local storage.
    Returns (bytes, content_type) or (None, None).
    """
    clean_key = (s3_key or "").lstrip("/")
    if not HAS_BOTO3:
        client = None
    else:
        client = _get_client()

    if client:
        for bucket in [_images_bucket(), _docs_bucket(), _staging_bucket(), _approved_bucket()]:
            try:
                resp = client.get_object(Bucket=bucket, Key=clean_key)
                body = resp["Body"].read()
                ctype = resp.get("ContentType", "image/png")
                return body, ctype
            except Exception as e:
                err_str = str(e)
                if "NoSuchKey" in err_str or "Not Found" in err_str or "404" in err_str:
                    logger.debug(f"S3 object '{clean_key}' not found in bucket '{bucket}': {e}")
                else:
                    logger.warning(f"Failed to fetch S3 object '{clean_key}' from bucket '{bucket}': {e}")

    # Fallback: check local disk storage folders
    fname = os.path.basename(clean_key)
    clean_norm = os.path.normpath(clean_key)
    for folder in ["data/temp", "data/images", "data/uploads", "data/documents", "data/storage"]:
        for candidate in [clean_key, clean_norm, fname]:
            local_path = os.path.normpath(os.path.join(folder, candidate))
            if os.path.exists(local_path) and os.path.isfile(local_path):
                try:
                    with open(local_path, "rb") as f:
                        file_bytes = f.read()
                    ext = os.path.splitext(fname)[1].lower()
                    mime_map = {
                        ".png": "image/png",
                        ".jpg": "image/jpeg",
                        ".jpeg": "image/jpeg",
                        ".webp": "image/webp",
                        ".pdf": "application/pdf",
                        ".json": "application/json"
                    }
                    return file_bytes, mime_map.get(ext, "image/png")
                except Exception:
                    pass

    return None, None


# ─── IMAGE STORAGE (bucket: images) ──────────────────────────────────────────

def upload_image(content: bytes, filename: str, content_type: str = "image/png") -> dict:
    """
    Synchronously uploads image binary content to images bucket (PUBLIC-READ).
    Falls back cleanly to local disk storage if MinIO is unavailable.
    """
    s3_key = f"images/{uuid.uuid4().hex}_{filename}"
    browser_url = _format_browser_url(None, s3_key)
    bucket_name = _images_bucket()

    # Always ensure local disk fallback copy exists
    _save_file_to_local_disk(content, filename, s3_key=s3_key)

    client = _get_client()
    if not client:
        return {
            "s3_key": s3_key,
            "image_url": browser_url,
            "size": len(content),
            "status": "fallback"
        }

    try:
        extra_args = {}
        if content_type:
            extra_args["ContentType"] = content_type

        client.put_object(
            Bucket=bucket_name,
            Key=s3_key,
            Body=content,
            **extra_args
        )

        logger.debug(f"✅ Successfully uploaded image '{filename}' to MinIO -> {browser_url}")
        return {
            "s3_key": s3_key,
            "image_url": browser_url,
            "size": len(content),
            "status": "success"
        }
    except Exception as e:
        logger.debug(f"MinIO upload note for '{filename}': {e}. Returning local proxy URL.")
        return {
            "s3_key": s3_key,
            "image_url": browser_url,
            "size": len(content),
            "status": "fallback"
        }


def upload_images_parallel(images: list) -> list:
    """
    Upload multiple images to MinIO concurrently using ThreadPoolExecutor.
    Falls back cleanly to local disk storage if MinIO is offline.
    """
    if not images:
        return []

    client = _get_client()
    bucket_name = _images_bucket() if client else None

    # Always save all images to local disk fallback storage
    for img in images:
        if img.get("content") and img.get("filename"):
            _save_file_to_local_disk(img["content"], img["filename"])

    if not client:
        results = []
        for img in images:
            s3_key = f"images/{uuid.uuid4().hex}_{img['filename']}"
            results.append({
                "s3_key": s3_key,
                "image_url": _format_browser_url(None, s3_key),
                "size": len(img.get("content", b"")),
                "status": "fallback"
            })
        return results

    def _upload_single(img_data: dict) -> dict:
        fname = img_data["filename"]
        content = img_data["content"]
        ctype = img_data.get("content_type", "image/png")
        s3_key = f"images/{uuid.uuid4().hex}_{fname}"
        browser_url = _format_browser_url(None, s3_key)
        try:
            extra_args = {}
            if ctype:
                extra_args["ContentType"] = ctype
            client.put_object(
                Bucket=bucket_name,
                Key=s3_key,
                Body=content,
                **extra_args
            )
            logger.debug(f"Uploaded '{fname}' to MinIO -> {browser_url}")
            return {
                "s3_key": s3_key,
                "image_url": browser_url,
                "size": len(content),
                "status": "success"
            }
        except Exception as e:
            logger.warning(f"MinIO upload failed for '{fname}': {e}")
            return {
                "s3_key": s3_key,
                "image_url": browser_url,
                "size": len(content),
                "status": "fallback"
            }

    from concurrent.futures import ThreadPoolExecutor
    with ThreadPoolExecutor(max_workers=min(len(images), 8)) as executor:
        results = list(executor.map(_upload_single, images))

    success_count = sum(1 for r in results if r["status"] == "success")
    logger.info(f"Parallel upload complete: {success_count}/{len(images)} images uploaded successfully.")
    return results


def get_presigned_url(s3_key: str, expires: int = 604800) -> str:
    """Generates presigned GET URL for an existing image object key (7 day default)."""
    clean_key = (s3_key or "").lstrip("/")
    try:
        raw_url = _generate_presigned_url(_images_bucket(), clean_key, expires)
        return _format_browser_url(raw_url, clean_key)
    except Exception as e:
        logger.warning(f"Failed to generate presigned URL for key '{clean_key}': {e}")
        return _format_browser_url(None, clean_key)


def delete_image(s3_key: str) -> None:
    """Deletes an image object from images bucket."""
    client = _get_client()
    if not client:
        return
    try:
        client.delete_object(Bucket=_images_bucket(), Key=s3_key)
        logger.info(f"Deleted image key '{s3_key}' from MinIO")
    except Exception as e:
        logger.debug(f"Failed to delete image key '{s3_key}' from MinIO: {e}")


# ─── DOCUMENT STORAGE (bucket: knowledge-documents) ──────────────────────────
# Original uploaded files and canonical JSON are stored here.
# Key pattern: originals/{year}/{month}/{document-id}/original.{ext}
#              canonical/{document-id}/document.json

def _build_document_s3_key(document_id: str, filename: str) -> str:
    """
    Builds the S3 key for an original document upload.
    Pattern: originals/{year}/{month}/{document-id}/original.{ext}
    """
    now = datetime.utcnow()
    ext = os.path.splitext(filename)[1].lower() if filename else ""
    return f"originals/{now.year}/{now.month:02d}/{document_id}/original{ext}"


def _build_canonical_s3_key(document_id: str) -> str:
    """
    Builds the S3 key for canonical JSON.
    Pattern: canonical/{document-id}/document.json
    """
    return f"canonical/{document_id}/document.json"


def upload_document(
    content: bytes,
    filename: str,
    document_id: str,
    content_type: str = "application/octet-stream"
) -> dict:
    """
    Uploads original document file to knowledge-documents bucket.
    Falls back cleanly to local disk storage if MinIO is offline.
    """
    s3_key = _build_document_s3_key(document_id, filename)
    bucket_name = _docs_bucket()

    _save_file_to_local_disk(content, filename, s3_key=s3_key)

    client = _get_client()
    if not client:
        return {
            "s3_key": s3_key,
            "bucket": bucket_name,
            "document_url": _format_browser_url(None, s3_key),
            "size": len(content),
            "status": "fallback"
        }

    try:
        extra_args = {}
        if content_type:
            extra_args["ContentType"] = content_type

        client.put_object(
            Bucket=bucket_name,
            Key=s3_key,
            Body=content,
            **extra_args
        )

        doc_url = _generate_presigned_url(bucket_name, s3_key, expires=3600)

        logger.info(f"📄 Uploaded original document '{filename}' -> {bucket_name}/{s3_key}")
        return {
            "s3_key": s3_key,
            "bucket": bucket_name,
            "document_url": doc_url,
            "size": len(content),
            "status": "success"
        }
    except Exception as e:
        logger.debug(f"Document upload to MinIO note for '{filename}': {e}")
        return {
            "s3_key": s3_key,
            "bucket": bucket_name,
            "document_url": _format_browser_url(None, s3_key),
            "size": len(content),
            "status": "fallback"
        }


def upload_canonical_json(document_id: str, canonical_data: dict) -> dict:
    """
    Uploads canonical JSON (approved document state) to knowledge-documents bucket.
    Key: canonical/{document-id}/document.json
    """
    s3_key = _build_canonical_s3_key(document_id)
    bucket_name = _docs_bucket()

    # Save to local disk output folder
    try:
        os.makedirs("data/output", exist_ok=True)
        with open(f"data/output/{document_id}.json", "w", encoding="utf-8") as f:
            json.dump(canonical_data, f, indent=2, ensure_ascii=False)
    except Exception:
        pass

    client = _get_client()
    if not client:
        return {"s3_key": s3_key, "bucket": bucket_name, "status": "fallback"}

    try:
        json_bytes = json.dumps(canonical_data, indent=2, ensure_ascii=False).encode("utf-8")
        client.put_object(
            Bucket=bucket_name,
            Key=s3_key,
            Body=json_bytes,
            ContentType="application/json"
        )

        logger.info(f"📋 Uploaded canonical JSON for '{document_id}' -> {bucket_name}/{s3_key}")
        return {"s3_key": s3_key, "bucket": bucket_name, "status": "success"}
    except Exception as e:
        logger.debug(f"Canonical JSON upload note for '{document_id}': {e}")
        return {"s3_key": s3_key, "bucket": bucket_name, "status": "fallback"}


# ─── STAGING & APPROVED JSON STORAGE (buckets: staging, approved) ────────────

def upload_staging_json(knowledge_id: str, data: dict) -> dict:
    """
    Uploads staging JSON to MinIO bucket 'staging' as source of truth.
    Mirrors to local disk cache 'data/pending/{knowledge_id}.json'.
    """
    s3_key = f"{knowledge_id}.json"
    bucket_name = _staging_bucket()

    # Mirror to local disk cache
    try:
        os.makedirs("data/pending", exist_ok=True)
        local_path = os.path.join("data/pending", s3_key)
        with open(local_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
    except Exception as e:
        logger.debug(f"Local staging cache write note: {e}")

    client = _get_client()
    if not client:
        return {"s3_key": s3_key, "bucket": bucket_name, "status": "fallback"}

    try:
        json_bytes = json.dumps(data, indent=2, ensure_ascii=False).encode("utf-8")
        client.put_object(
            Bucket=bucket_name,
            Key=s3_key,
            Body=json_bytes,
            ContentType="application/json"
        )
        logger.info(f"📥 Uploaded staging JSON for '{knowledge_id}' -> {bucket_name}/{s3_key}")
        return {"s3_key": s3_key, "bucket": bucket_name, "status": "success"}
    except Exception as e:
        logger.debug(f"Staging JSON upload note for '{knowledge_id}': {e}")
        return {"s3_key": s3_key, "bucket": bucket_name, "status": "fallback"}


def get_staging_json(knowledge_id: str) -> Optional[dict]:
    """
    Retrieves staging JSON from MinIO 'staging' bucket (source of truth).
    If found in MinIO, updates/refreshes local disk cache in 'data/pending/{knowledge_id}.json'.
    Falls back to local disk if MinIO is offline or object not found in MinIO.
    """
    s3_key = f"{knowledge_id}.json"
    bucket_name = _staging_bucket()
    client = _get_client()

    if client:
        try:
            resp = client.get_object(Bucket=bucket_name, Key=s3_key)
            raw = resp["Body"].read().decode("utf-8")
            data = json.loads(raw)
            # Update local disk cache
            try:
                os.makedirs("data/pending", exist_ok=True)
                with open(os.path.join("data/pending", s3_key), "w", encoding="utf-8") as f:
                    f.write(raw)
            except Exception:
                pass
            return data
        except Exception:
            pass

    # Fallback to local disk cache
    for candidate in [
        os.path.join("data/pending", f"{knowledge_id}.json"),
        os.path.join("data/pending", f"{knowledge_id}_parsed.json"),
    ]:
        if os.path.exists(candidate):
            try:
                with open(candidate, "r", encoding="utf-8") as f:
                    return json.load(f)
            except Exception:
                pass

    return None


def upload_approved_json(knowledge_id: str, data: dict) -> dict:
    """
    Uploads approved JSON to MinIO bucket 'approved' as source of truth.
    Mirrors to local disk cache 'data/output/{knowledge_id}.json'.
    Also maintains backward compatibility with canonical JSON in docs bucket.
    """
    s3_key = f"{knowledge_id}.json"
    bucket_name = _approved_bucket()

    # Mirror to local disk cache
    try:
        os.makedirs("data/output", exist_ok=True)
        local_path = os.path.join("data/output", s3_key)
        with open(local_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
    except Exception as e:
        logger.debug(f"Local approved cache write note: {e}")

    client = _get_client()
    if not client:
        return {"s3_key": s3_key, "bucket": bucket_name, "status": "fallback"}

    try:
        json_bytes = json.dumps(data, indent=2, ensure_ascii=False).encode("utf-8")
        client.put_object(
            Bucket=bucket_name,
            Key=s3_key,
            Body=json_bytes,
            ContentType="application/json"
        )
        logger.info(f"✅ Uploaded approved JSON for '{knowledge_id}' -> {bucket_name}/{s3_key}")
        # Maintain canonical JSON in knowledge-documents for backward compatibility
        try:
            upload_canonical_json(knowledge_id, data)
        except Exception:
            pass
        return {"s3_key": s3_key, "bucket": bucket_name, "status": "success"}
    except Exception as e:
        logger.debug(f"Approved JSON upload note for '{knowledge_id}': {e}")
        return {"s3_key": s3_key, "bucket": bucket_name, "status": "fallback"}


def get_approved_json(knowledge_id: str) -> Optional[dict]:
    """
    Retrieves approved JSON from MinIO 'approved' bucket (source of truth).
    If found in MinIO, updates/refreshes local disk cache in 'data/output/{knowledge_id}.json'.
    Falls back to local disk if MinIO is offline.
    """
    s3_key = f"{knowledge_id}.json"
    bucket_name = _approved_bucket()
    client = _get_client()

    if client:
        try:
            resp = client.get_object(Bucket=bucket_name, Key=s3_key)
            raw = resp["Body"].read().decode("utf-8")
            data = json.loads(raw)
            # Update local disk cache
            try:
                os.makedirs("data/output", exist_ok=True)
                with open(os.path.join("data/output", s3_key), "w", encoding="utf-8") as f:
                    f.write(raw)
            except Exception:
                pass
            return data
        except Exception:
            pass

    # Fallback to local disk cache
    for candidate in [
        os.path.join("data/output", f"{knowledge_id}.json"),
        os.path.join("data/output", f"{knowledge_id}_parsed.json"),
    ]:
        if os.path.exists(candidate):
            try:
                with open(candidate, "r", encoding="utf-8") as f:
                    return json.load(f)
            except Exception:
                pass

    return None


def promote_staging_to_approved(knowledge_id: str, data: dict) -> dict:
    """
    Promotes document from staging to approved:
    1. Uploads to MinIO 'approved' bucket and writes 'data/output/{knowledge_id}.json'.
    2. Deletes from MinIO 'staging' bucket and deletes 'data/pending/{knowledge_id}.json'.
    """
    res = upload_approved_json(knowledge_id, data)
    delete_staging_json(knowledge_id)
    return res


def delete_staging_json(knowledge_id: str) -> None:
    """Deletes staging JSON from MinIO 'staging' bucket and local pending cache."""
    s3_key = f"{knowledge_id}.json"
    client = _get_client()
    if client:
        try:
            client.delete_object(Bucket=_staging_bucket(), Key=s3_key)
            logger.info(f"Deleted staging JSON '{s3_key}' from MinIO '{_staging_bucket()}'")
        except Exception as e:
            logger.debug(f"Failed to delete staging JSON from MinIO: {e}")

    # Remove local cache files
    for path in [
        os.path.join("data/pending", f"{knowledge_id}.json"),
        os.path.join("data/pending", f"{knowledge_id}_parsed.json")
    ]:
        if os.path.exists(path):
            try:
                os.remove(path)
            except Exception:
                pass


def delete_approved_json(knowledge_id: str) -> None:
    """Deletes approved JSON from MinIO 'approved' bucket and local output cache."""
    s3_key = f"{knowledge_id}.json"
    client = _get_client()
    if client:
        try:
            client.delete_object(Bucket=_approved_bucket(), Key=s3_key)
            logger.info(f"Deleted approved JSON '{s3_key}' from MinIO '{_approved_bucket()}'")
        except Exception as e:
            logger.debug(f"Failed to delete approved JSON from MinIO: {e}")

    # Remove local cache files
    for path in [
        os.path.join("data/output", f"{knowledge_id}.json"),
        os.path.join("data/output", f"{knowledge_id}_parsed.json")
    ]:
        if os.path.exists(path):
            try:
                os.remove(path)
            except Exception:
                pass


def sync_existing_local_to_minio() -> dict:
    """
    Initial sync: uploads any existing local files in 'data/pending' to 'staging' bucket
    and 'data/output' to 'approved' bucket in MinIO so MinIO is immediately populated
    as the Source of Truth.
    """
    synced_staging = 0
    synced_approved = 0
    client = _get_client()
    if not client:
        return {"staging": 0, "approved": 0, "status": "offline"}

    staging_bucket = _staging_bucket()
    approved_bucket = _approved_bucket()

    # 1. Sync data/pending -> staging
    if os.path.exists("data/pending"):
        for fname in os.listdir("data/pending"):
            if fname.endswith(".json") and not fname.endswith("_history.json"):
                kid = fname[:-5].replace("_parsed", "")
                full_path = os.path.join("data/pending", fname)
                try:
                    with open(full_path, "r", encoding="utf-8") as f:
                        data = json.load(f)
                    json_bytes = json.dumps(data, indent=2, ensure_ascii=False).encode("utf-8")
                    client.put_object(
                        Bucket=staging_bucket,
                        Key=f"{kid}.json",
                        Body=json_bytes,
                        ContentType="application/json"
                    )
                    synced_staging += 1
                except Exception as e:
                    logger.debug(f"Sync pending file '{fname}' note: {e}")

    # 2. Sync data/output -> approved
    if os.path.exists("data/output"):
        for fname in os.listdir("data/output"):
            if fname.endswith(".json") and not fname.endswith("_history.json"):
                kid = fname[:-5].replace("_parsed", "")
                full_path = os.path.join("data/output", fname)
                try:
                    with open(full_path, "r", encoding="utf-8") as f:
                        data = json.load(f)
                    json_bytes = json.dumps(data, indent=2, ensure_ascii=False).encode("utf-8")
                    client.put_object(
                        Bucket=approved_bucket,
                        Key=f"{kid}.json",
                        Body=json_bytes,
                        ContentType="application/json"
                    )
                    synced_approved += 1
                except Exception as e:
                    logger.debug(f"Sync approved file '{fname}' note: {e}")

    if synced_staging > 0 or synced_approved > 0:
        logger.info(f"🔄 Synced local files to MinIO: {synced_staging} staging, {synced_approved} approved.")
    return {"staging": synced_staging, "approved": synced_approved, "status": "success"}


def get_document_presigned_url(s3_key: str, expires: int = 3600) -> str:
    """Generates presigned GET URL for a document (1 hour default — shorter for security)."""
    return _generate_presigned_url(_docs_bucket(), s3_key, expires)


def delete_document_file(s3_key: str) -> None:
    """Deletes a document object from knowledge-documents bucket."""
    client = _get_client()
    if not client:
        return
    try:
        client.delete_object(Bucket=_docs_bucket(), Key=s3_key)
        logger.info(f"Deleted document key '{s3_key}' from MinIO")
    except Exception as e:
        logger.debug(f"Failed to delete document key '{s3_key}' from MinIO: {e}")


def clear_all_buckets() -> dict:
    """
    Deletes ALL objects across ALL buckets in MinIO.
    Re-initializes required buckets ('images', 'knowledge-documents', 'staging', 'approved') and policies afterwards.
    """
    if not HAS_BOTO3:
        return {"status": "skipped", "reason": "boto3 not installed"}

    deleted_counts = {}
    try:
        client = _get_client()

        # Scan ALL buckets currently in MinIO
        all_b_res = client.list_buckets()
        bucket_names = [b["Name"] for b in all_b_res.get("Buckets", [])]

        # Always include active configured buckets
        for target_b in [_images_bucket(), _docs_bucket(), _staging_bucket(), _approved_bucket(), "images", "knowledge-documents", "staging", "approved"]:
            if target_b not in bucket_names:
                bucket_names.append(target_b)

        for bucket_name in set(bucket_names):
            count = 0
            try:
                paginator = client.get_paginator('list_objects_v2')
                for page in paginator.paginate(Bucket=bucket_name):
                    objects = page.get('Contents', [])
                    for obj in objects:
                        try:
                            client.delete_object(Bucket=bucket_name, Key=obj['Key'])
                            count += 1
                        except Exception as del_err:
                            logger.warning(f"Error deleting object '{obj['Key']}' from bucket '{bucket_name}': {del_err}")
                deleted_counts[bucket_name] = count
                logger.info(f"🗑️ Cleared {count} objects from MinIO bucket '{bucket_name}'.")
            except Exception as b_err:
                logger.warning(f"Error clearing MinIO bucket '{bucket_name}': {b_err}")
                deleted_counts[bucket_name] = count

        ensure_all_buckets()
        return {"status": "success", "deleted_counts": deleted_counts}
    except Exception as e:
        logger.error(f"clear_all_buckets failed: {e}")
        return {"status": "error", "message": str(e)}


