"""S3-compatible dual-bucket object storage via boto3 (MinIO, AWS S3, etc.).

Bucket architecture:
  images                → embedded images from documents (private, presigned URL access)
  knowledge-documents   → original uploaded documents + canonical JSON (private, presigned URL access)

Both buckets are PRIVATE. All access goes through presigned URLs generated by the application API.
"""
import os
import json
import uuid
from datetime import datetime
from typing import Optional
from loguru import logger
from app.core.config import settings

try:
    import boto3
    from botocore.config import Config
    HAS_BOTO3 = True
except ImportError:
    boto3 = None
    Config = None
    HAS_BOTO3 = False


# ─── Bucket Names ─────────────────────────────────────────────────────────────

def _images_bucket() -> str:
    """Bucket for embedded images extracted from documents."""
    return os.getenv("S3_BUCKET") or settings.S3_BUCKET or "images"


def _docs_bucket() -> str:
    """Bucket for original uploaded documents and canonical JSON."""
    return os.getenv("S3_DOCUMENTS_BUCKET") or settings.S3_DOCUMENTS_BUCKET or "knowledge-documents"


# ─── S3 Client ─────────────────────────────────────────────────────────────────

def _get_client():
    """
    Creates boto3 S3 client with automatic fallback across docker network (http://minio:9000)
    and host localhost (http://localhost:9000).
    """
    endpoints = []
    env_endpoint = os.getenv("S3_ENDPOINT_URL") or settings.S3_ENDPOINT_URL
    if env_endpoint:
        endpoints.append(env_endpoint)
    # Add standard docker and host fallbacks
    for ep in ["http://minio:9000", "http://localhost:9000", "http://127.0.0.1:9000"]:
        if ep not in endpoints:
            endpoints.append(ep)

    access_key = os.getenv("S3_ACCESS_KEY") or settings.S3_ACCESS_KEY or "minioadmin"
    secret_key = os.getenv("S3_SECRET_KEY") or settings.S3_SECRET_KEY or "minioadmin"
    region = os.getenv("S3_REGION") or settings.S3_REGION or "us-east-1"
    use_path_style = settings.S3_USE_PATH_STYLE if hasattr(settings, "S3_USE_PATH_STYLE") else True

    for endpoint_url in endpoints:
        try:
            client = boto3.client(
                "s3",
                endpoint_url=endpoint_url,
                aws_access_key_id=access_key,
                aws_secret_access_key=secret_key,
                config=Config(
                    signature_version="s3v4",
                    s3={"addressing_style": "path" if use_path_style else "auto"},
                    connect_timeout=3,
                    read_timeout=5,
                    retries={'max_attempts': 2}
                ),
                region_name=region,
            )
            # Test connectivity
            client.list_buckets()
            return client
        except Exception:
            continue

    # Fallback to primary configured endpoint
    primary_ep = endpoints[0] if endpoints else "http://localhost:9000"
    return boto3.client(
        "s3",
        endpoint_url=primary_ep,
        aws_access_key_id=access_key,
        aws_secret_access_key=secret_key,
        config=Config(
            signature_version="s3v4",
            s3={"addressing_style": "path" if use_path_style else "auto"}
        ),
        region_name=region,
    )


# ─── Bucket Initialization ────────────────────────────────────────────────────

def _ensure_bucket_private(bucket_name: str) -> None:
    """Ensures a MinIO bucket exists with PRIVATE access (no public read)."""
    try:
        client = _get_client()
        try:
            client.head_bucket(Bucket=bucket_name)
        except Exception:
            client.create_bucket(Bucket=bucket_name)
            logger.info(f"Created MinIO bucket (private): '{bucket_name}'")
    except Exception as e:
        logger.warning(f"Could not connect or ensure MinIO bucket '{bucket_name}': {e}")


def _ensure_images_bucket() -> None:
    """Ensures images bucket exists with PUBLIC-READ policy so URLs never expire."""
    bucket_name = _images_bucket()
    try:
        client = _get_client()
        try:
            client.head_bucket(Bucket=bucket_name)
        except Exception:
            client.create_bucket(Bucket=bucket_name)
            logger.info(f"Created MinIO bucket: '{bucket_name}'")

        # Set public read policy so browser/frontend can view images directly
        # Images use STATIC URLs that never expire — not presigned URLs
        policy = {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Principal": "*",
                    "Action": ["s3:GetObject"],
                    "Resource": [f"arn:aws:s3:::{bucket_name}/*"]
                }
            ]
        }
        try:
            client.put_bucket_policy(Bucket=bucket_name, Policy=json.dumps(policy))
        except Exception:
            pass
    except Exception as e:
        logger.warning(f"Could not ensure images bucket '{bucket_name}': {e}")


def _ensure_docs_bucket() -> None:
    """Ensures knowledge-documents bucket exists with PRIVATE access."""
    _ensure_bucket_private(_docs_bucket())


def _build_static_image_url(bucket_name: str, s3_key: str) -> str:
    """
    Builds a static (non-expiring) image URL for the public-read images bucket.
    Uses localhost:9000 for browser access (converts docker-internal minio:9000).
    """
    # Always return browser-accessible URL
    return f"http://localhost:9000/{bucket_name}/{s3_key}"


def ensure_all_buckets() -> None:
    """Initialize both buckets at application startup.
    - images: PUBLIC-READ (static URLs, never expire)
    - knowledge-documents: PRIVATE (presigned URLs only)
    """
    _ensure_images_bucket()
    _ensure_docs_bucket()
    logger.info(f"MinIO buckets initialized: '{_images_bucket()}' (public-read), '{_docs_bucket()}' (private)")


# ─── Presigned URL Generation ─────────────────────────────────────────────────

def _generate_presigned_url(bucket_name: str, s3_key: str, expires: int = 604800) -> str:
    """
    Generates presigned GET URL for an S3 object.
    All access is via presigned URLs (both buckets are PRIVATE).
    Default expiry: 7 days for images, callers can override.
    """
    try:
        client = _get_client()
        raw_url = client.generate_presigned_url(
            "get_object",
            Params={"Bucket": bucket_name, "Key": s3_key},
            ExpiresIn=expires
        )
        # Convert docker-internal URL to browser-accessible URL
        if "minio:9000" in raw_url:
            raw_url = raw_url.replace("minio:9000", "localhost:9000")
        return raw_url
    except Exception as e:
        logger.warning(f"Failed to generate presigned URL for '{bucket_name}/{s3_key}': {e}")
        return f"http://localhost:9000/{bucket_name}/{s3_key}"


# ─── IMAGE STORAGE (bucket: images) ──────────────────────────────────────────
# These functions handle embedded images extracted from documents during parsing.
# The existing key pattern `images/{uuid}_{filename}` is preserved.

def upload_image(content: bytes, filename: str, content_type: str = "image/png") -> dict:
    """
    Synchronously uploads image binary content to images bucket (PUBLIC-READ).
    Returns s3_key & STATIC browser-accessible image_url (never expires).
    """
    s3_key = f"images/{uuid.uuid4().hex}_{filename}"
    bucket_name = _images_bucket()

    if not HAS_BOTO3:
        logger.warning(f"boto3 package not installed. Returning fallback image info for '{filename}'.")
        return {
            "s3_key": s3_key,
            "image_url": _build_static_image_url(bucket_name, s3_key),
            "size": len(content),
            "status": "fallback"
        }
    try:
        _ensure_images_bucket()
        client = _get_client()

        extra_args = {}
        if content_type:
            extra_args["ContentType"] = content_type

        client.put_object(
            Bucket=bucket_name,
            Key=s3_key,
            Body=content,
            **extra_args
        )

        # Static URL — images bucket is PUBLIC-READ, URLs never expire
        image_url = _build_static_image_url(bucket_name, s3_key)

        logger.info(f"✅ Successfully uploaded image '{filename}' to MinIO -> {s3_key}")
        return {
            "s3_key": s3_key,
            "image_url": image_url,
            "size": len(content),
            "status": "success"
        }
    except Exception as e:
        logger.warning(f"MinIO upload failed for '{filename}': {e}. Returning fallback URL.")
        return {
            "s3_key": s3_key,
            "image_url": _build_static_image_url(bucket_name, s3_key),
            "size": len(content),
            "status": "fallback"
        }


def upload_images_parallel(images: list) -> list:
    """
    Upload multiple images to MinIO concurrently using ThreadPoolExecutor.
    Initializes S3 client ONCE, then uploads all images in parallel.

    Args:
        images: List of dicts with keys: 'content' (bytes), 'filename' (str), 'content_type' (str)

    Returns:
        List of dicts with keys: 's3_key', 'image_url', 'size', 'status' (in same order as input)
    """
    if not images:
        return []

    if not HAS_BOTO3:
        logger.warning("boto3 not installed. Returning fallback URLs for all images.")
        results = []
        bucket_name = _images_bucket()
        for img in images:
            s3_key = f"images/{uuid.uuid4().hex}_{img['filename']}"
            results.append({
                "s3_key": s3_key,
                "image_url": f"http://localhost:9000/{bucket_name}/{s3_key}",
                "size": len(img.get("content", b"")),
                "status": "fallback"
            })
        return results

    # Initialize client and ensure bucket ONCE (not per-image)
    try:
        _ensure_images_bucket()
        client = _get_client()
        bucket_name = _images_bucket()
    except Exception as e:
        logger.warning(f"MinIO init failed: {e}. Returning fallback URLs.")
        results = []
        bucket_name = _images_bucket()
        for img in images:
            s3_key = f"images/{uuid.uuid4().hex}_{img['filename']}"
            results.append({
                "s3_key": s3_key,
                "image_url": f"http://localhost:9000/{bucket_name}/{s3_key}",
                "size": len(img.get("content", b"")),
                "status": "fallback"
            })
        return results

    def _upload_single(img_data: dict) -> dict:
        fname = img_data["filename"]
        content = img_data["content"]
        ctype = img_data.get("content_type", "image/png")
        s3_key = f"images/{uuid.uuid4().hex}_{fname}"
        try:
            extra_args = {}
            if ctype:
                extra_args["ContentType"] = ctype
            client.put_object(
                Bucket=bucket_name,
                Key=s3_key,
                Body=content,
                **extra_args
            )
            # Static URL — images bucket is PUBLIC-READ
            image_url = _build_static_image_url(bucket_name, s3_key)
            logger.info(f"Uploaded '{fname}' to MinIO -> {s3_key}")
            return {
                "s3_key": s3_key,
                "image_url": image_url,
                "size": len(content),
                "status": "success"
            }
        except Exception as e:
            logger.warning(f"MinIO upload failed for '{fname}': {e}")
            return {
                "s3_key": s3_key,
                "image_url": _build_static_image_url(bucket_name, s3_key),
                "size": len(content),
                "status": "fallback"
            }

    from concurrent.futures import ThreadPoolExecutor
    with ThreadPoolExecutor(max_workers=min(len(images), 8)) as executor:
        results = list(executor.map(_upload_single, images))

    success_count = sum(1 for r in results if r["status"] == "success")
    logger.info(f"Parallel upload complete: {success_count}/{len(images)} images uploaded successfully.")
    return results


def get_presigned_url(s3_key: str, expires: int = 604800) -> str:
    """Generates presigned GET URL for an existing image object key (7 day default)."""
    return _generate_presigned_url(_images_bucket(), s3_key, expires)


def delete_image(s3_key: str) -> None:
    """Deletes an image object from images bucket."""
    try:
        client = _get_client()
        client.delete_object(Bucket=_images_bucket(), Key=s3_key)
        logger.info(f"Deleted image key '{s3_key}' from MinIO")
    except Exception as e:
        logger.warning(f"Failed to delete image key '{s3_key}' from MinIO: {e}")


# ─── DOCUMENT STORAGE (bucket: knowledge-documents) ──────────────────────────
# Original uploaded files and canonical JSON are stored here.
# Key pattern: originals/{year}/{month}/{document-id}/original.{ext}
#              canonical/{document-id}/document.json

def _build_document_s3_key(document_id: str, filename: str) -> str:
    """
    Builds the S3 key for an original document upload.
    Pattern: originals/{year}/{month}/{document-id}/original.{ext}
    """
    now = datetime.utcnow()
    ext = os.path.splitext(filename)[1].lower() if filename else ""
    return f"originals/{now.year}/{now.month:02d}/{document_id}/original{ext}"


def _build_canonical_s3_key(document_id: str) -> str:
    """
    Builds the S3 key for canonical JSON.
    Pattern: canonical/{document-id}/document.json
    """
    return f"canonical/{document_id}/document.json"


def upload_document(
    content: bytes,
    filename: str,
    document_id: str,
    content_type: str = "application/octet-stream"
) -> dict:
    """
    Uploads original document file to knowledge-documents bucket.
    Key: originals/{year}/{month}/{document-id}/original.{ext}

    Returns: {"s3_key", "bucket", "document_url", "size", "status"}
    """
    s3_key = _build_document_s3_key(document_id, filename)
    bucket_name = _docs_bucket()

    if not HAS_BOTO3:
        logger.warning(f"boto3 not installed. Cannot upload document '{filename}'.")
        return {
            "s3_key": s3_key,
            "bucket": bucket_name,
            "document_url": None,
            "size": len(content),
            "status": "fallback"
        }

    try:
        _ensure_docs_bucket()
        client = _get_client()

        extra_args = {}
        if content_type:
            extra_args["ContentType"] = content_type

        client.put_object(
            Bucket=bucket_name,
            Key=s3_key,
            Body=content,
            **extra_args
        )

        doc_url = _generate_presigned_url(bucket_name, s3_key, expires=3600)

        logger.info(f"📄 Uploaded original document '{filename}' -> {bucket_name}/{s3_key}")
        return {
            "s3_key": s3_key,
            "bucket": bucket_name,
            "document_url": doc_url,
            "size": len(content),
            "status": "success"
        }
    except Exception as e:
        logger.warning(f"Document upload to MinIO failed for '{filename}': {e}")
        return {
            "s3_key": s3_key,
            "bucket": bucket_name,
            "document_url": None,
            "size": len(content),
            "status": "fallback"
        }


def upload_canonical_json(document_id: str, canonical_data: dict) -> dict:
    """
    Uploads canonical JSON (approved document state) to knowledge-documents bucket.
    Key: canonical/{document-id}/document.json

    Returns: {"s3_key", "bucket", "status"}
    """
    s3_key = _build_canonical_s3_key(document_id)
    bucket_name = _docs_bucket()

    if not HAS_BOTO3:
        logger.warning(f"boto3 not installed. Cannot upload canonical JSON for '{document_id}'.")
        return {"s3_key": s3_key, "bucket": bucket_name, "status": "fallback"}

    try:
        _ensure_docs_bucket()
        client = _get_client()

        json_bytes = json.dumps(canonical_data, indent=2, ensure_ascii=False).encode("utf-8")
        client.put_object(
            Bucket=bucket_name,
            Key=s3_key,
            Body=json_bytes,
            ContentType="application/json"
        )

        logger.info(f"📋 Uploaded canonical JSON for '{document_id}' -> {bucket_name}/{s3_key}")
        return {"s3_key": s3_key, "bucket": bucket_name, "status": "success"}
    except Exception as e:
        logger.warning(f"Canonical JSON upload failed for '{document_id}': {e}")
        return {"s3_key": s3_key, "bucket": bucket_name, "status": "fallback"}


def get_document_presigned_url(s3_key: str, expires: int = 3600) -> str:
    """Generates presigned GET URL for a document (1 hour default — shorter for security)."""
    return _generate_presigned_url(_docs_bucket(), s3_key, expires)


def delete_document_file(s3_key: str) -> None:
    """Deletes a document object from knowledge-documents bucket."""
    try:
        client = _get_client()
        client.delete_object(Bucket=_docs_bucket(), Key=s3_key)
        logger.info(f"Deleted document key '{s3_key}' from MinIO")
    except Exception as e:
        logger.warning(f"Failed to delete document key '{s3_key}' from MinIO: {e}")


def clear_all_buckets() -> dict:
    """
    Deletes ALL objects across ALL buckets in MinIO.
    Re-initializes required buckets ('images' and 'knowledge-documents') and policies afterwards.
    """
    if not HAS_BOTO3:
        return {"status": "skipped", "reason": "boto3 not installed"}

    deleted_counts = {}
    try:
        client = _get_client()

        # Scan ALL buckets currently in MinIO
        all_b_res = client.list_buckets()
        bucket_names = [b["Name"] for b in all_b_res.get("Buckets", [])]

        # Always include active configured buckets
        for target_b in [_images_bucket(), _docs_bucket(), "images", "knowledge-documents"]:
            if target_b not in bucket_names:
                bucket_names.append(target_b)

        for bucket_name in set(bucket_names):
            count = 0
            try:
                paginator = client.get_paginator('list_objects_v2')
                for page in paginator.paginate(Bucket=bucket_name):
                    objects = page.get('Contents', [])
                    for obj in objects:
                        try:
                            client.delete_object(Bucket=bucket_name, Key=obj['Key'])
                            count += 1
                        except Exception as del_err:
                            logger.warning(f"Error deleting object '{obj['Key']}' from bucket '{bucket_name}': {del_err}")
                deleted_counts[bucket_name] = count
                logger.info(f"🗑️ Cleared {count} objects from MinIO bucket '{bucket_name}'.")
            except Exception as b_err:
                logger.warning(f"Error clearing MinIO bucket '{bucket_name}': {b_err}")
                deleted_counts[bucket_name] = count

        ensure_all_buckets()
        return {"status": "success", "deleted_counts": deleted_counts}
    except Exception as e:
        logger.error(f"clear_all_buckets failed: {e}")
        return {"status": "error", "message": str(e)}

