"""Add external_id, code, ecosystem to branch

Revision ID: 09a7966682b6
Revises: 2352bcc97f16
Create Date: 2026-08-07 03:20:57.325800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09a7966682b6'
down_revision: Union[str, None] = '2352bcc97f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_arya_noble_kb_embedding_hnsw'), table_name='arya_noble_kb', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '100'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_arya_noble_kb_source_file'), table_name='arya_noble_kb')
    op.drop_table('arya_noble_kb')
    op.add_column('branches', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('branches', sa.Column('code', sa.String(), nullable=True))
    op.add_column('branches', sa.Column('ecosystem', sa.String(), server_default='Erha', nullable=False))
    op.create_unique_constraint(None, 'branches', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'branches', type_='unique')
    op.drop_column('branches', 'ecosystem')
    op.drop_column('branches', 'code')
    op.drop_column('branches', 'external_id')
    op.create_table('arya_noble_kb',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_file', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('arya_noble_kb_pkey'))
    )
    op.create_index(op.f('ix_arya_noble_kb_source_file'), 'arya_noble_kb', ['source_file'], unique=False)
    op.create_index(op.f('idx_arya_noble_kb_embedding_hnsw'), 'arya_noble_kb', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '100'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
