"""Update KnowledgeType enum

Revision ID: 270b0f97d577
Revises: f55b221777db
Create Date: 2026-07-21 05:52:17.412297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '270b0f97d577'
down_revision: Union[str, None] = 'f55b221777db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("TRUNCATE TABLE knowledge CASCADE")
    op.execute("ALTER TYPE knowledge_type RENAME TO knowledge_type_old")
    op.execute("CREATE TYPE knowledge_type AS ENUM('PRODUCT', 'TREATMENT', 'PROMOTIONAL', 'GENERAL')")
    op.execute("ALTER TABLE knowledge ALTER COLUMN type TYPE knowledge_type USING type::text::knowledge_type")
    op.execute("DROP TYPE knowledge_type_old")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
