"""Add doctor fields to users table

Revision ID: a2b3c4d5e6f7
Revises: f659a76eeecf
Create Date: 2026-07-28 23:01:45.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b3c4d5e6f7'
down_revision = 'f659a76eeecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employee_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('dr_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('ecosystem', sa.String(), server_default='ERHA', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ecosystem')
    op.drop_column('users', 'dr_type')
    op.drop_column('users', 'employee_id')
    # ### end Alembic commands ###
