"""remove_unused_branch_columns

Revision ID: ef5f540160e5
Revises: 09a7966682b6
Create Date: 2026-08-07 03:29:28.286424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef5f540160e5'
down_revision: Union[str, None] = '09a7966682b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'longitude')
    op.drop_column('branches', 'address')
    op.drop_column('branches', 'latitude')
    op.drop_column('branches', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('branches', sa.Column('latitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True))
    op.add_column('branches', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('branches', sa.Column('longitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
