"""Add AppConfig and has_ai_access

Revision ID: f20560dfb5dd
Revises: 1a1ed105c9b5
Create Date: 2026-07-19 20:17:38.702988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f20560dfb5dd'
down_revision: Union[str, None] = '1a1ed105c9b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_config_key'), 'app_config', ['key'], unique=True)
    op.add_column('users', sa.Column('has_ai_access', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_ai_access')
    op.drop_index(op.f('ix_app_config_key'), table_name='app_config')
    op.drop_table('app_config')
    # ### end Alembic commands ###
