"""Add HNSW index and TSVectorType to KnowledgeChunk

Revision ID: f55b221777db
Revises: f20560dfb5dd
Create Date: 2026-07-21 03:23:47.117228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f55b221777db'
down_revision: Union[str, None] = 'f20560dfb5dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_chunk', sa.Column('searchable_content', postgresql.TSVECTOR(), nullable=True))
    op.create_index('ix_knowledge_chunk_embedding', 'knowledge_chunk', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_knowledge_chunk_searchable_content', 'knowledge_chunk', ['searchable_content'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_chunk_searchable_content', table_name='knowledge_chunk', postgresql_using='gin')
    op.drop_index('ix_knowledge_chunk_embedding', table_name='knowledge_chunk', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_column('knowledge_chunk', 'searchable_content')
    # ### end Alembic commands ###
